### ISSUE TITLE
Add compatibility with keep-oilwell script

### ISSUE THREAD

**Issue by Mat40** [CodineDev/cdn-fuel#15]
Hi can you add compatibility with [keep-oilweel](https://github.com/swkeep/keep-oilwell) script. 
This script add petrol companies.
It will be good if gas station owner can buy gas to petrol companies

**Comment by dnelyk** [comment]
This change is planned after the Stable Release of 2.0.0 and we move from Beta.

Can be found here on the roadmap: https://github.com/CodineDev/cdn-fuel/wiki/Player-Owned-Gasoline-(Gas)-Ergonomic-Refueling-Stations-(POGGERS)#future-plans-no-timeframe-on-these-changes
