### ISSUE TITLE
QB-Menu Options Greyed Out (Player Owned Gas Stations)

### ISSUE THREAD

**Issue by dnelyk** [CodineDev/cdn-fuel#17]
The reason for the issue has been found but, the way for the fix will not be implemented into the main branch, and users will have to alter themselves. 

With confidence, someone figured out that when there is a slower database connection, the callbacks can be slow, resulting in their being a false reading on the result, automatically assuming that the location is purchased and that the person who is opening the menu is not the owner, causing all options for the main menu to be greyed out.

Fortunately, there is a pretty simple fix. Users can up the Wait() functions to ~100 or more (nothing over 250 is recommended, as menu(s) responsiveness will be quite slow). This should fix the issue and we are pretty positive this is the problem. 

If you are having the issue, try the task mentioned above to see if the problem persists, if it does, feel free to test other fixes, and we can attempt to get those mentioned here and/or add the main branch.

**Comment by Homer199090** [comment]
I have tried all the fix but unfortunately it remains gray for me
![xvWx9E3](https://github.com/CodineDev/cdn-fuel/assets/124883757/e4dd3517-8844-414a-be6a-2be13f34ea45)
![xvWx9E3](https://github.com/CodineDev/cdn-fuel/assets/124883757/f73e1d94-816c-4105-8ed7-ac878f54317a)
