### ISSUE TITLE
Electric vehicle issues

### ISSUE THREAD

**Issue by MarcusPlayz517** [CodineDev/cdn-fuel#18]
- Whilst using `Config.RenewedPhonePayment = true`, when paying with bank for electric vehicle, after accepting the payment on the phone there is no way to charge the vehicle, it just takes your money.

- Cash doesn't get removed when charging an electric vehicle all the way through the progress bar, but it will charge the vehicle. To further this if you cancel the progress bar, cash will be removed and vehicle will be charged to the amount.

- Error when charging an electric vehicle all the way through the progress bar, to further this the error only shows when you charge an electric vehicle first after a restart, if you refuel a vehicle up with gas then charge an electric vehicle you do not get the error. [screenshot](https://i.imgur.com/NBsIGRe.jpeg)

**Comment by dnelyk** [comment]
**Issues should now be fixed.**

 If you encounter any more issues, make an issue here or discuss it in our discord!

_See Commit:_ https://github.com/CodineDev/cdn-fuel/commit/cdb5c4c495395011eea54d2c42a676acc5124cbe
