### ISSUE TITLE
CreateBlip Error

### ISSUE THREAD

**Issue by ohbrime** [CodineDev/cdn-fuel#19]
Create closest Blip doesn't work for some reason. Only works normally when it shows all Blips.

Error on line: 165 in fuel_cl.lua

![image](https://user-images.githubusercontent.com/70352847/209760651-3bb989df-395b-42fc-947d-74fb9e6918bc.png)

**Comment by AndreasFromDanmark** [comment]
getting same error

**Comment by dnelyk** [comment]
Cannot replicate this issue with Config.ShowNearestGasStationOnly = true, on the latest patch. Are there any particular steps needed to replicate? If not, I would consider this either fixed or non-replicable.

**Comment by ohbrime** [comment]
I have fixed the issie stated in one of my pull requests. That method helped and removed error and it works perfectly fine. Some other people had that issue as well.

**Comment by NonameCommunity** [comment]
Same issue guys any fix?

**Comment by ohbrime** [comment]
Yes, i posted it in a Pull Request.

**Comment by NonameCommunity** [comment]
thx man :)

**Comment by ohbrime** [comment]
if Config.ShowNearestGasStationOnly then 
         CreateThread(function() 
                 TriggerServerEvent('cdn-fuel:server:updatelocationlabels') 
                 Wait(1000) 
                 local currentGasBlip = 0 
                 while true do 
                         local coords = GetEntityCoords(PlayerPedId()) 
                         local closest = 1000 
                         local closestCoords 
                         local closestLocation 
                         local label 
                         local location = 0 
                         for _, ourCoords in pairs(Config.GasStations) do 
                                 location = location + 1 
                                 local gasStationCoords = vector3(Config.GasStations[location].pedcoords.x, Config.GasStations[location].pedcoords.y, Config.GasStations[location].pedcoords.z) 
                                 local dstcheck = #(coords - gasStationCoords) 
                                 if dstcheck < closest then 
                                         closest = dstcheck 
                                         closestCoords = gasStationCoords 
                                         closestLocation = location 
                                         label = Config.GasStations[closestLocation].label 
                                 end 
                         end 
                         if DoesBlipExist(currentGasBlip) then 
                                 RemoveBlip(currentGasBlip) 
                         end 
                         currentGasBlip = CreateBlip(closestCoords, label) 
                         Wait(10000) 
                 end 
         end) 
 else 
         CreateThread(function() 
                 TriggerServerEvent('cdn-fuel:server:updatelocationlabels') 
                 Wait(500) 
                 local location = 0 
                 for _, ourCoords in pairs(Config.GasStations) do 
                         location = location + 1 
                         local gasStationCoords = vector3(Config.GasStations[location].pedcoords.x, Config.GasStations[location].pedcoords.y, Config.GasStations[location].pedcoords.z) 
                         local label = Config.GasStations[location].label 
                         CreateBlip(gasStationCoords, label) 
                 end 
         end) 
 end

**Comment by ohbrime** [comment]
This is the full fix.

**Comment by NonameCommunity** [comment]
its working but if i buy a gas station and change the name it does not change on the map

**Comment by ohbrime** [comment]
You need to drive to one of the other nearest gasstations and then comeback then it will show that its updated.

**Comment by NonameCommunity** [comment]
oh ok

**Comment by dnelyk** [comment]
Should be fixed:

https://github.com/CodineDev/cdn-fuel/commit/ab01dcb501e8ced6178b1a11473ee75934169379
