### ISSUE TITLE
Jerry cans arent working

### ISSUE THREAD

**Issue by Krisb239** [CodineDev/cdn-fuel#26]
The Jerry cans are not working. You can purchase them but cant use them or fill them up with fuel. the syphon kit is working fine. I've followed the installation guide to a T 3x over. Im really not sure if i missed something or what. Its racking my brain lol.

**Comment by jnccloud** [comment]
Make sure you've added the code to inventory's JS. After that, you need to grab the nozzle from the pump and then use the new jerry can item you purchased from the pump. You need to do the same thing at a car, I think using the item will allow you to fuel the car then if you are near the back of the car.

**Comment by dnelyk** [comment]
Equip the jerry can while using the nozzle, and you can refuel the jerrycan.
