### ISSUE TITLE
attempt to compare nil with number

### ISSUE THREAD

**Issue by BPJ-Project** [CodineDev/cdn-fuel#29]
gas stations currently not owned by anyone but set to true all stations have fuel in them  and getting this error when select cash or bank to buy fuel. jerry can working fine just not vehicles
https://i.imgur.com/eov8zkF.png

RegisterNetEvent('cdn-fuel:client:FinalMenu', function(purchasetype)
	FetchStationInfo("all")
	Wait(100)
	if Config.PlayerOwnedGasStationsEnabled and not Config.UnlimitedFuel then 
		if ReserveLevels < 1 then
			QBCore.Functions.Notify(Lang:t("station_no_fuel"), 'error', 7500) return
		end
	end
	local money = nil
	if purchasetype == "bank" then money = QBCore.Functions.GetPlayerData().money['bank'] elseif purchasetype == 'cash' then money = QBCore.Functions.GetPlayerData().money['cash'] end
	if Config.PlayerOwnedGasStationsEnabled then
		FuelPrice = (1 * StationFuelPrice)
	else
		FuelPrice = (1 * Config.CostMultiplier)
	end

**Comment by BPJ-Project** [comment]
just double checked once the script has thrown this error once then everyone is able to buy fuel using cash or bank untill the error has been thrown once it doesnt work

**Comment by dnelyk** [comment]
The FetchStationInfo('all') check is probably taking longer than the 100ms allotted. This could be due to a slow database or just the volume of data being requested. I recommend that you up the Wait(100) until the issue is resolved.
