### ISSUE TITLE
error nil value

### ISSUE THREAD

**Issue by Mat40** [CodineDev/cdn-fuel#35]
Hi when `Config.PlayerOwnedGasStationsEnabled = true ` this error occur : 
![image](https://user-images.githubusercontent.com/59476172/212746537-70214ec5-7fca-437d-b1a5-ae7961faf899.png)

**Comment by dnelyk** [comment]
There is nothing on that line that pertains to values and numbers, you have an out-of-date version so try and install the latest and see if the issue persists.
