### ISSUE TITLE
Fuel Target Export

### ISSUE THREAD

**Issue by Snakyermagerd** [CodineDev/cdn-fuel#37]
When you set Fuel Target Export to true it takes away the explosion when running away with the nozzle. This also keeps the nozzle in your hand and does not remove even when you put it back.

**Comment by dnelyk** [comment]
You probably have blacklisted explosions or something as with the latest version, with FuelTargetExport enabled & explosion enabled the pump explodes, and the nozzle is removed. 

The nozzle is also removed when putting it back on the pump. 

Make sure you followed the install guide correctly for the fuel target export.

**Comment by Snakyermagerd** [comment]
Yeah it's fixed now, my apologies.
