### ISSUE TITLE
Players refueling non owned vehicles

### ISSUE THREAD

**Issue by Provokke** [CodineDev/cdn-fuel#38]
Players are not able to refuel vehicles that are not owned to them. I feel players should be able to fill up local or other players vehicle for numerous reasons, and or a option to turn on and off in config.

**Comment by dnelyk** [comment]
What portion is this referring to? 

Base Fueling, Syphoning or Jerry Cans?

**Comment by Provokke** [comment]
Base Fueling

**Comment by dnelyk** [comment]
Because of the way that fuel usage is handled, I don't think it would be possible to fix this issue unfortunately.
