### ISSUE TITLE
[Suggestion] - ox conversation

### ISSUE THREAD

**Issue by FilipeCuco** [CodineDev/cdn-fuel#41]
is it possible for you to convert the script to ox?
https://github.com/overextended/ox_lib
https://github.com/overextended/ox_inventory

**Comment by dnelyk** [comment]
There is someone in the community that created an ox version of the script for users of ox_inventory and ox_libs. 

This is not our script, but from what I have seen, it does work. We cannot provide support for anything related to OX though unfortunately.

Repository: https://github.com/NoobySloth/cdn-fuel-ox

**Comment by dnelyk** [comment]
@FilipeCuco 

The support has been added via Configurable Options in the latest patch of CDN-Fuel!
