### ISSUE TITLE
PlayerOwned Issue

### ISSUE THREAD

**Issue by FiveOPZ** [CodineDev/cdn-fuel#44]
PlayerOwned Gas stations show up grey but i have it set to true in the config why can i not buy a gas station when i speak to the guy?

Also is there a CDN-Fuel discord server?

**Comment by dnelyk** [comment]
https://github.com/CodineDev/cdn-fuel/issues/17 will fix your issue. 

Here is the discord: https://discord.gg/FBgeJy6t

**Comment by FiveOPZ** [comment]
Also found out had to set the callback to 300 appreciate it
