### ISSUE TITLE
Fuel nozzle

### ISSUE THREAD

**Issue by EnchantedBrwny** [CodineDev/cdn-fuel#47]
**Describe the bug**

When placing the nozzle back the nozzle does not despawn and you are forced to refresh your skin. Also the debug poly zone stuff is still here even when debug = false.

**To Reproduce**
1. Go to 'Gas pump'
2. Click on 'Grab nozzle'
3. Return the nozzle

**Comment by dnelyk** [comment]
Issue described should be fixed in the latest patch!
