### ISSUE TITLE
Debug polyzones always showing (2.1.0)

### ISSUE THREAD

**Issue by Mitch-Altman** [CodineDev/cdn-fuel#48]
**Describe the bug**
I keep seeing the poly debug zones surrounding the gas stations with the new 2.1.0 update

**To Reproduce**
1. Drive towards a gas station 
2. You will see this: 

![image](https://user-images.githubusercontent.com/86323279/230796056-6c802861-4830-400a-a08c-35f40c30d7e5.png)

**Expected behavior**
A way to turn it off so you won't see the debug polyzones

**Additional context**
I did seen a commit of 'added debug poly'. I placed the line `Config.PolyDebug = false -- Enables Polyzone Debugging to see PolyZones!` into my config but nothing changed

**Comment by dnelyk** [comment]
Issue described should be fixed in the latest patch!
