### ISSUE TITLE
Unable to purchase fuel

### ISSUE THREAD

**Issue by l3oncoder** [CodineDev/cdn-fuel#50]
Hi there, I've installed cdn-fuel to my QBox install and followed the steps for ox_libs , up on inserting the nozzle into car, i get the following message [You have to fuel more than 0L] not sure how to fix this, No errors in F8 or server console thanks,

**Comment by dnelyk** [comment]
This issue will be addressed in the next patch which will happen in a bit, just fixing some other issues. I will send another message once this issue is fixed on the main branch!

Thanks!

**Comment by dnelyk** [comment]
@l3oncoder This issue has been addressed in the latest patch available here: https://github.com/CodineDev/cdn-fuel/commit/8e09e768d33a467ab36390e9c98683b37fdf1a6f

Thank you for using cdn-fuel!

Be sure to make us aware of any other issues you encounter!

**Comment by l3oncoder** [comment]
Thanks works perfectly  to what I can see :D
