### ISSUE TITLE
Prop Model Bug

### ISSUE THREAD

**Issue by imtorchedbud** [CodineDev/cdn-fuel#51]
**When You are done fueling the nozzle prop does not disappear out of your hands possibly just need to utilize /propfix /refreshskin to get it out of your hands can still register that in hands and didn't return it so chance to blowup is still active**

**To Reproduce**
1. Go to 'pump'
2. Click on 'grab nozzle'
4. 2. Click on 'grab nozzle'
5. Scroll down to 'No Error Showing / or no print active there'
6. See error null?

**Expected behavior**
just return the nozzle and remove prop from hands utilzing a client function i can add in through a fork

**Screenshots | Video**
If applicable, add screenshots or video to help explain your problem.
https://i.imgur.com/LGFjbXZ.png ~ grab nozzle pic
https://i.imgur.com/ZQm9JC6.jpeg ~ return nozzle pic
https://i.imgur.com/8Drskxk.jpeg  ~ prop stuck pic
**Additional context**
nothign works perfect other than that just still iffy when you refuel at stations even with qb target client export for can refuel  and i also made a cdn fool to make sure we can restart if we ever needed to which we never have.

**Comment by dnelyk** [comment]
Could not replicate this issue. Make sure to download the latest release / zip to ensure this error is not caused by an out-of-date build.
