### ISSUE TITLE
[Suggestion] - Config selection for Liters vs Gallons

### ISSUE THREAD

**Issue by LowestCarb** [CodineDev/cdn-fuel#54]
**Is your feature request related to a problem? Please describe.**
No, more of a preference. My concern is when I make the all the changes to show "Gallons" I'll have to make the changes myself every time we get an update of this script.

**Describe the solution you'd like**
A config parameter that changes all fuel labels to show a consumer determined string. (i.e. Gallons, Liters, Car Juice, etc.)

**Describe alternatives you've considered**
Changing all the labels myself. I plan to do this for now, but it would be awesome to not have to for every script update.

**Additional context**
N/A - Should be self explanatory.

**Comment by dnelyk** [comment]
This should be a fairly simple thing to add, so next feature update will include it.
