### ISSUE TITLE
Whitelist Fuel Pumps Issues

### ISSUE THREAD

**Issue by ChickenDipper1** [CodineDev/cdn-fuel#55]
When setting Air and Water fueling to whitelisted jobs, the following error shows in the console and you cannot access the pump:

![image](https://user-images.githubusercontent.com/41157940/232206964-1e0703a3-65f7-4556-af04-bee3394a8588.png)

**Comment by RoyalGPO** [comment]
from what i can see its QBCore.Functions.Notify(Lang:t("nozzle_cannot_reach"), 'error')

and i think it might be due to either you don't have the Lang:t( thing in the translastions for qbcore 
or it might be with nozzle_cannot_reach translasions that is mission a coma ,

**Comment by dnelyk** [comment]
Let me know if this issue is still prevalent in the latest update:
https://github.com/CodineDev/cdn-fuel/releases/tag/2.1.2

**Comment by Roydeking52** [comment]
How did you change it to jobs?

**Comment by dnelyk** [comment]
This issue should be fixed in the latest update, available here: https://github.com/CodineDev/cdn-fuel/releases/tag/2.1.5, thanks for your help in tracing the issue!
