### ISSUE TITLE
Qb-Target/menu gone too fast when choosing gas station ped

### ISSUE THREAD

**Issue by Bigfudge87** [CodineDev/cdn-fuel#57]
**Describe the bug**
When i use Qb-Target/menu i can get the list over what to to. but the list disappears too fast so i do not have the time to choose something. 

**To Reproduce**
1. Go to 'ped at gasstation'
2. Click on 'qb-target and then try too chose something in the menu'

**Expected behavior**
i expect to have enough time to do something  in the menu

**Screenshots | Video**
the menu in the picture disappears too fast
![image](https://user-images.githubusercontent.com/131615238/233859201-554f0f8c-075d-463d-ba68-ab94f506a80f.png)  

**Additional context**

**Comment by LowestCarb** [comment]
I've had a bug similar to this in the past, make sure you don't have another script running something close by that would close that menu. For me it was qb-boombox

**Comment by dnelyk** [comment]
As stated in this comment: https://github.com/CodineDev/cdn-fuel/issues/57#issuecomment-1528998168; the issue derives from something else, and we cannot reproduce this issue, so this will be closed.
