### ISSUE TITLE
[Suggestion] - OX input

### ISSUE THREAD

**Issue by Airidas-Fix** [CodineDev/cdn-fuel#58]
**Is your feature request related to a problem? Please describe.**

Add missing part who is using ox_lib on fuel_cl.lua because now i see only qb-input but for example I dont use any qb-input everything is ox so can you guys add for ox input ?

**Comment by Airidas-Fix** [comment]
Because looks like in fuel_cl.lua you guys missed adding ox input

**Comment by dnelyk** [comment]
This issue should be fixed with the latest release: 
https://github.com/CodineDev/cdn-fuel/releases/tag/2.1.2

Thanks for supporting us by using CDN-Fuel! Hopefully, your issue is fixed.
