### ISSUE TITLE
Tiny bug when using OX

### ISSUE THREAD

**Issue by mikepauer** [CodineDev/cdn-fuel#60]
**Describe the bug**
Installing the latest (as of 20 minutes ago) against a full qbx + ox install, found gas works fine, but refilling jerrycan's did not

**To Reproduce**
Buy Jerry Can, Refill Jerry Can, Jerry can fuel amount stays 0

**Expected behavior**
Jerrycan should have purchased fuel

**Additional context**
Already know the problem and solution, but didn't want to create git environment to push the fix for a tiny thing
The problem is in fuel_cl.lua, line 1548, it currently pushes the string 'jerrycan' to cdn-fuel:info instead of itemData.

**Comment by mikepauer** [comment]
Also line 1205 (Ox input refill menu) is using Lang:t("menu_header_refuel_jerry_can") instead of Lang:t("menu_header_refuel_vehicle")

**Comment by dnelyk** [comment]
This issue should be fixed with the latest release: 
https://github.com/CodineDev/cdn-fuel/releases/tag/2.1.2

Thanks for supporting us by using CDN-Fuel! Hopefully, your issue is fixed.
