### ISSUE TITLE
Jerry can refueling issue

### ISSUE THREAD

**Issue by alberttheprince** [CodineDev/cdn-fuel#66]
Seems that jerry cans aren't functioning/refilling atm.

**Comment by Baksteen1991** [comment]
Open client/fuel_cl.lua find line 1705(If it is standard and you have not made modifications then replace the code with the following)

            if Config.Ox.Inventory then
                    local amount = tonumber(refuel.amount)
                    TriggerServerEvent('cdn-fuel:info', "add", amount, srcPlayerData, 'jerrycan')
                else
                    local amount = tonumber(refuel.amount)
                    TriggerServerEvent('cdn-fuel:info', "add", amount, srcPlayerData, jerryCanData)
                end

**Comment by alberttheprince** [comment]
Thank you Baksteen!

**Comment by ysprinsessie** [comment]
> Open client/fuel_cl.lua find line 1705(If it is standard and you have not made modifications then replace the code with the following)
> 
> ```
>         if Config.Ox.Inventory then
>                 local amount = tonumber(refuel.amount)
>                 TriggerServerEvent('cdn-fuel:info', "add", amount, srcPlayerData, 'jerrycan')
>             else
>                 local amount = tonumber(refuel.amount)
>                 TriggerServerEvent('cdn-fuel:info', "add", amount, srcPlayerData, jerryCanData)
>             end
> ```

Thank you, this fixed the issue for me.

**Comment by Baksteen1991** [comment]
😃 Awesome! Glad I could help.

**Comment by dnelyk** [comment]
This issue should be fixed in the latest update, available here: https://github.com/CodineDev/cdn-fuel/releases/tag/2.1.5, thanks for your help in tracing the issue!
