### ISSUE TITLE
Jerry can bug

### ISSUE THREAD

**Issue by DonXoxo** [CodineDev/cdn-fuel#71]
**Describe the bug**
The jerry can does not refuel again despite money being debited from account.

**To Reproduce**
1. Go to 'gas station'
2. Click on 'jerrycan'
3. Scroll down to 'jerrycan'
4. See error @cdn-fuel/server/fuel_sv.lua:200: attempt to perform arithmetic on a nil value (local 'amount')

**Expected behavior**
Jerry can does not refill

**Screenshots | Video**
None

**Additional context**
None

**Comment by dnelyk** [comment]
This issue should be fixed in the latest update, available here: https://github.com/CodineDev/cdn-fuel/releases/tag/2.1.5, thanks for your help in tracing the issue!
