### ISSUE TITLE
the nozzle cannot be returned

### ISSUE THREAD

**Issue by atpizza** [CodineDev/cdn-fuel#73]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots | Video**
If applicable, add screenshots or video to help explain your problem.

**Additional context**
![Screenshot (127)](https://github.com/CodineDev/cdn-fuel/assets/102321644/6566f54d-2bcd-45a7-b294-1956375ffbc1)
can take the nozzle, but cannot be returned back

**Comment by atpizza** [comment]
https://github.com/CodineDev/cdn-fuel/assets/102321644/f693afc3-1acb-4b8d-b83d-f689b4da9680

**Comment by atpizza** [comment]
i fixed, sorry

**Comment by xyced** [comment]
I have the same issue right now, how did you fix it?

**Comment by brains1960** [comment]
@xyced Remove the numbers (e.g. "num: 1") for the options, it doesn't like that the earlier options are missing apparently
