### ISSUE TITLE
PlayJob

### ISSUE THREAD

**Issue by atpizza** [CodineDev/cdn-fuel#74]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots | Video**
If applicable, add screenshots or video to help explain your problem.

**Additional context**
![Screenshot (128)](https://github.com/CodineDev/cdn-fuel/assets/102321644/8688699d-e45d-45bf-9e3a-5edff1f27157)

**Comment by dnelyk** [comment]
I think I understand why this issue is occurring, and I am currently working on the solution. It will be fixed in the next update, which will fix all known remaining issues, which will be coming very soon. Thank you for reporting the issue.

**Comment by dnelyk** [comment]
This issue should be fixed in the latest update, available here: https://github.com/CodineDev/cdn-fuel/releases/tag/2.1.5, thanks for your help in tracing the issue!
