### ISSUE TITLE
[BUG] Blip

### ISSUE THREAD

**Issue by M4RFY** [CodineDev/cdn-fuel#78]
**Random Gas Station Blip**

When you use the 'nearest gas station' feature, a random blip appears in the center of the map. However, when you get close to a fuel station, it disappears. But, when you're not within the fuel station's range, it reappears.

**Comment by rayzenoam** [comment]
Hello there, @M4RFY

Simply go to the `fuel_cl.lua` file, then search for `local closest = 1000` and adjust the value until you have a balance between your gas stations.

And there you go!
